spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 1024
    url: jdbc:mysql://127.0.0.1:3309/sell?characterEncoding=utf-8&useSSL=false
    username: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
env:
 dev
